### ISSUE TITLE
ImportError: No module name setuptools

### ISSUE THREAD

**Issue by Warrior-4-Christ** [dnet/pySSTV#13]
```
$ python ./setup.py
Traceback (most recent call last):
  File "./setup.py", line 3, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```

How do I fix this?  I'm running Ubuntu 16.04

**Comment by dnet** [comment]
From the [accepted answer in first result in Google for `ImportError: No module named setuptools`](https://stackoverflow.com/a/14426553):

> To install this on Debian:
>
> `sudo apt-get install python-setuptools`
>
> For Python 3.x
>
> `sudo apt-get install python3-setuptools`

I'm not sure what version of Python is the default on Ubuntu 16.04, do these work for you?
