### ISSUE TITLE
Mode PD 

### ISSUE THREAD

**Issue by sp2ong** [dnet/pySSTV#16]
Hi,

It will be nice to have mode PD   
http://www.classicsstv.com/pdmodes.php

**Comment by dnet** [comment]
Why did you open and then close this issue?

**Comment by sp2ong** [comment]
Sorry, I have closed because I did not receive any comment that is is possible or interesting to add to pySSTV

but I am open again

**Comment by dnet** [comment]
Is this a feature request, or would you like to implement it yourself?

**Comment by sp2ong** [comment]
Is this a feature reques

**Comment by dnet** [comment]
Sorry it took so long, I released v0.4 [on GitHub](https://github.com/dnet/pySSTV/releases/tag/v0.4) and [on PyPI](https://pypi.python.org/pypi/PySSTV/0.4).
