### ISSUE TITLE
Playing slowly

### ISSUE THREAD

**Issue by zeke800** [dnet/pySSTV#30]
Hi, thank you for the great software!!

I am running the following command

python -m pysstv --mode PD180 --vox /media/pi/2655-2656/STS-1/sstv_image.jpg --keep-aspect-ratio --rate 44100 sstv_image_sts_1.wav 

slowrx fails to decode the image, outputting garbage. When I listen to the wav file, it seems to be playing very slowly, at half speed or something. 

Any ideas how to get this working?

Thank you!

**Comment by dnet** [comment]
How long is the resulting `sstv_image_sts_1.wav` according to your player? Can you upload that file as an attachment to this issue?

**Comment by dnet** [comment]
I also [used this on a Raspberry Pi](https://hsbp.org/rpi-sstv) (and the first release of the Pi, which got even less power) so I'd guess it has more to do with the software you used to play the resulting WAV file with and the DAC (either the built-in or a USB sound device).
