### ISSUE TITLE
Failing when run on Python 3.5.1

### ISSUE THREAD

**Issue by FlyingLotus1983** [dnet/pySSTV#8]
When running from Python 3.5.1, I get the following error:

```
[...] 
pysstv/sstv.py", line 7, in <module>
    from itertools import imap, izip, cycle, chain
ImportError: cannot import name 'imap' 
```

Per: http://python-future.org/compatible_idioms.html#imap some workarounds need to be made as imap has been deprecaded, as well as izip.

I will attempt to make these changes and send a pull request.  Per the URL above the changes should be backwards compatible with python 2.  If I discover any other problems along the way, I'll fix thoses as well.

**Comment by KM4YRI** [comment]
The pull request linked above should fix the issue.
